import asyncio
from fastapi.testclient import TestClient
from main import app
import json

client = TestClient(app)

mock_api1_batch = {
    "total_images": 2,
    "results": [
        {
            "filename": "shirt.jpg",
            "material_type": "Cotton",
            "fiber_category": "Natural",
            "description": "Breathable cotton.",
            "dirt_level": 3,
            "confidence_score": 0.95,
            "is_retry": False,
            "error": None
        },
        {
            "filename": "pants.jpg",
            "material_type": "Polyester",
            "fiber_category": "Synthetic",
            "description": "Durable synthetic.",
            "dirt_level": 5,
            "confidence_score": 0.90,
            "is_retry": False,
            "error": None
        }
    ],
    "hint": None
}

def run_test():
    # Save the mock response to a temporary JSON file
    with open("test_batch.json", "w") as f:
        json.dump(mock_api1_batch, f)

    with open("test_batch.json", "rb") as f:
        files = {"file": ("test_batch.json", f, "application/json")}
        print("Sending test request to /predict-from-file...")
        response = client.post("/predict-from-file", files=files)
        
    print(f"Status Code: {response.status_code}")
    if response.status_code == 200:
        data = response.json()
        print("\n=== BATCH SUMMARY ===")
        print(f"Total Predicted: {data['total_predicted']}")
        print(f"Machine Settings (Generated by AI):")
        print(json.dumps(data["machine_settings"], indent=2))
        print(f"\nNotes: {data['notes']}")
    else:
        print(f"Error: {response.text}")

if __name__ == "__main__":
    run_test()
